//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterEntityLogin : DbContext
    {
        public MasterEntityLogin()
            : base("name=MasterEntityLogin")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLoginTable> UserLoginTables { get; set; }

        public System.Data.Entity.DbSet<Project.Models.ViewModel.UserSignUpView> UserSignUpViews { get; set; }
    }
}
